#
# Since hypixel uses it's own protocol system to support newer clients, It will be filtered out from tampering with versions.
#
client-side-force-disable:
- hypixel.net
- '*.hypixel.net'
client-side-version: -2
enable-client-side: true
hide-button: false
