#
# Modifies the recipe book system to make it better,
# A portion of settings are disabled such as "unlockAll" to avoid causing problems.
#

enablePinning = true
darkMode = false
keepCentered = true
settingsButton = false
enableBook = true

[newRecipes]
unlockAll = false
enableBounce = true

[instantCraft]
showButton = false

[alternativeRecipes]
onHover = true
noGrouped = false

[scrolling]
enableScrolling = true
scrollAround = false
