# 
# Configures more items for 1.9 - 1.13+ servers for compatibility mode.
# 
always-show-original-mob-name: true
add-custom-enchants-into-lore: true
add-teamcolor-to-prefix: true
fix-1_13-face-player: true
